version: '3.3'

services:
  wordpress: 
    image: wordpress:${WP_VERSION}
    ports: 
      - 5000:80
    environment:
      WP_VERSION:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: test
    volumes:
      - ./src/app:/var/www/html/wp-content
      - ./src/wp:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpswd
 
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
