version: '3.3'

services:
  wp: 
    container_name: ${PROJECT_NAME}-wp
    image: wordpress:${WP_VERSION}
    ports: 
      - 5000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./docker/wordpress:/var/www/html
    networks:
      - project

  db:
    container_name: ${PROJECT_NAME}-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
    volumes:
      - ./docker/mysql:/var/lib/mysql/
    networks:
      - project

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - project

networks:
  project:
