version: '3.3'

services:
  wordpress: 
    image: wordpress:latest
    ports: 
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: test
    volumes:
      - ./src/plugins:/var/www/html/wp-content/plugins/
      - ./src/themes:/var/www/html/wp-content/themes/

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: rootpswd
    volumes:
      - ./mysql:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8081:80
