version: '3.8'

services:
  wordpress: 
    container_name: ${PROJECT_NAME}-wordpress
    image: wordpress:${WP_VERSION}
    ports: 
      - 5000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEFAULT_THEME', 'starter');
    volumes:
      - ./app:/var/www/html/wp-content/
    networks:
      - project

  db:
    container_name: ${PROJECT_NAME}-database
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
    volumes:
      - ./database:/var/lib/mysql/
    networks:
      - project

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - project

networks:
  project:
